### ISSUE TITLE
Can't move documents with 3.0.0.stable

### ISSUE THREAD

**Issue by hdak1945git** [smoreau/redmine_document_move#1]
I've tried this plugin with **3.0.0.stable** and it failed to present the option of moving any document. Nothing noteworthy to report from any of my logs.

Two other (largely) documentation issues:
1. It wasn't noted in the README, but this plugin added a new permission attribute (discovered by looking through the source code). I initially thought this was the source of my problem (none of my roles had it enabled).
2. Placing the plugin in `vendor/plugins` will also cause redmine to enter a loop with an warning in the application log: `Plugins in vendor/plugins (*scrub*) are no longer allowed. Please, put your Redmine plugins in the 'plugins' directory at the root of your Redmine directory (*scrub*)` The page then will fail to load with a timeout. Placing the plugin in the recommended directory (`{REDMINE_ROOT}/plugins`) solves this.

I'm not much of a ruby coder, so in the end, upgrading redmine to **3.0.3.stable** solved this issue, at least for me.

**Comment by smoreau** [comment]
I unfortunately cannot test this plugin on the 3.0.0.stable version. I started to develop this plugin under the version 3.0.1.stable.
However, I checked the code of the view on the Redmine github and the page didn't change between these two versions. So I am not sure where the problem is.

I think the reason why it didn't work on the 3.0.0.stable version is because it needs an additional gems (`deface`). In order to install the new gems, you need to execute the command `bundle update`. This is something I will also add to the README file.

**Comment by smoreau** [comment]
Redmine is currently on version 5.
This issue is now irrelevant.
